BEGIN begin;
END end;
SPACE ('\t'|' ')*;
NEWLINE '\n';
COMPARATORS (==)|>|(>=)|<|(<=);
ASSIGN =;
WHILE while;
DO do;
OD od;
IF if;
FI fi;
THEN then;
ELSE else;
VALUE (-(0|1|2|3|4|5|6|7|8|9)+)|((0|1|2|3|4|5|6|7|8|9)+);
OPERATORS -|'+'|'*'|/|%;
BRACKETS_OPEN '(';
BRACKETS_CLOSE ')';
VARIABLE (a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)+;